filebeat.inputs:
  - type: filestream
    paths:
      - '/var/lib/docker/containers/*/*.log'
    parsers:
      - container:
          stream: stdout
          format: docker
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - drop_event:
          when:
            not:
              or:
                - equals:
                    container.name: "portfolios-api-mongo-backend"

output.logstash:
  hosts: ["logstash:5044"]
